### ISSUE TITLE
Project Lead Meetup - Invites and Plans!

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#1]
Bringing together our stellar community members! :family: To learn and build together :mortar_board: 

https://kt.etherpad.mozilla.org/collaborate-project-lead-workweek

owner: @kaythaney 
- [x] Invite List 
- [x] Invite Text 
  - [x] First Draft @kaythaney 
  - [x] questions for form @zee-moz & @acabunoc (monday)
  - [x] setup google form for RSVP - add skillshare / location / challenge / project @acabunoc
- [x] Sketch for curriculum / event
  - [x] figure out what to do Monday night -- allow ppl to get rest / mingle - @arlissc 
  - [x] user research! fill out people list @zee-moz 
- [x] Reach out to Alex - cover travel logistics @arlissc 

@kaythaney @zee-moz

Digging into this at 4:00

**Comment by kaythaney** [comment]
thanks, abby!

**Comment by abbycabs** [comment]
@zee-moz -- I shared a form with you for putting together the RSVP form! Please hack away :)

**Comment by abbycabs** [comment]
I think we got through a lot of these yesterday! 
@arlissc & @zee-moz do you want to check off what's done? Maybe we can close this issue :)

:heavy_check_mark: :rocket:
