### ISSUE TITLE
Printed items for MozFest

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#12]
Things can get hectic at MozFest! Let's print off some items to help orient people :page_with_curl: 
- science space schedule handouts / @acabunoc
  - [x] design -- once we know floor / rooms for locations
  - [x] print
- pathway schedules - @joeyklee ?
  - [ ] ?
- collect all these buttons info - maybe just a sign with all the button images?
  - [x] add all buttons to this issue in a comment / @acabunoc & @zee-moz 
  - [x] design limited edition buttons sheet / @zee-moz 
  - [x] design pathways / general button sheet / @stephwright
  - [x] print
- DNA stickers / @acabunoc 
  - [x] labels ordered, shipped to london office / @kaythaney
  - [x] @acabunoc - print!

@joeyklee, I know you were thinking about this. Any ideas?

**Comment by abbycabs** [comment]
Pathway buttons:

![acceleratorgif 1](https://cloud.githubusercontent.com/assets/617994/10866929/55446b8e-8005-11e5-9038-174f7257073a.gif)
![citsci 1](https://cloud.githubusercontent.com/assets/617994/10866930/57200562-8005-11e5-8dda-99928e15d204.gif)
![opendatagif 1](https://cloud.githubusercontent.com/assets/617994/10866931/592bc29c-8005-11e5-8e53-c4ae3a0dd44d.gif)
![scicommgif 1](https://cloud.githubusercontent.com/assets/617994/10866932/5b8f563e-8005-11e5-9642-a5715dd62800.gif)

**Comment by zee-moz** [comment]
I put the limited editions button images on a single sheet. There aren't many! ~10 each fellow/staff person, so we can figure some kind of challenge that people need to complete to get them. If you didn't tell me what kind of image you wanted on your button I made one up for you!
![buttonfinder](https://cloud.githubusercontent.com/assets/13855390/10887445/0c369f0e-817f-11e5-94ba-6a847061971c.png)

**Comment by abbycabs** [comment]
@zee-moz I love it!

**Comment by arlissc** [comment]
@zee-moz - ME TOO !

**Comment by abbycabs** [comment]
@zee-moz you're... an alien?

**Comment by blahah** [comment]
@zee-moz :bow: sensei

**Comment by stephwright** [comment]
So much :heart_eyes:  @zee-moz !!!

**Comment by kaythaney** [comment]
these are ACE. thanks, @zee-moz!

**Comment by stephwright** [comment]
[PathwayButtons.pdf](https://github.com/mozillascience/plan/files/26702/PathwayButtons.pdf)
First attempt.  Other ideas for how one "earns" a button?  Or how they retrieve them?  Also need hashtags for pathways.  @Blahah and I have discussion on this in Gitter.

**Comment by stephwright** [comment]
Already realized I didn't have the full name of Open Research Accelerator on above PDF.  Have updated source doc but waiting to hear back on hashtags before or whatever earnings / retrieval mechanism we come up with before uploading again.

**Comment by abbycabs** [comment]
Really like this! Thanks :)

**Comment by stephwright** [comment]
Happy to do it! Looking forward to finishing up the details.

**Comment by stephwright** [comment]
Alright... updated version.  Ready to print... I think. :heavy_check_mark: 
[PathwayButtons.pdf](https://github.com/mozillascience/plan/files/27885/PathwayButtons.pdf)

**Comment by abbycabs** [comment]
done printing things!

**Comment by abbycabs** [comment]
schedule:
[schedule_mozfest2015.pdf](https://github.com/mozillascience/plan/files/28579/schedule_mozfest2015.pdf)

**Comment by abbycabs** [comment]
closing!
