### ISSUE TITLE
Post MozFest work

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#18]
- [x] Facilitator followup (may have been done by @arlissc ?)
  - http://goo.gl/forms/mLxihMSoUw sent to facilitators
- [x] collect etherpads / github repos for projects 
  - https://public.etherpad-mozilla.org/p/sciencelab-mozfest-2015-session-etherpads
- [x] find community call speakers
- [x] find guest blog posts
  - in form sent by @arlissc 
- [x] Raffle follow-up - @arlissc 
  - [x] input in spreadsheet - @arlissc & @acabunoc
  - [x] write copy for followup emails - @acabunoc
    - https://docs.google.com/a/mozilla.com/document/d/1Ms6GE9TReW5uSjBgHgolN7ZesuQWEqkzvma2yq61xYU/edit?usp=sharing
  - [x] individually email 'contribute to open science project' - @acabunoc
  - [x] individually email 'start an open science study group' - @acabunoc (most of these also want to contribute to an open science project. will use one email for both)
  - [x] add to mailing list
- [x] Blog / @arlissc

**Comment by abbycabs** [comment]
@arlissc - what's the current status of the raffle & facilitator follow-up? 

Or... who has the tickets? @stephwright?

**Comment by stephwright** [comment]
Tickets were put into the bag of stuff to go back, I believe.  @kaythaney did that go home with you? raffle winner has already been notified.

**Comment by abbycabs** [comment]
Follow up for more info (study groups, contributing) should ideally be done <48h after the event! Would love to get on that if someone has the emails.

**Comment by kaythaney** [comment]
Nope, raffle tickets are with @arlissc. Arliss - possible to tackle today? Let us know if you need help!

**Comment by kaythaney** [comment]
@acabunoc + @arlissc - worth reaching out to facilitators again today to collect materials used for their sessions, work done, links, etc?

**Comment by abbycabs** [comment]
@arlissc want me to setup an etherpad / github repo to collect all the materials? We can ask facilitators to contribute or email us.

**Comment by abbycabs** [comment]
@arlissc has a master etherpad with info on shared materials for all sessions! She'll send it to @kaythaney to include in the blog :)

**Comment by arlissc** [comment]
@acabunoc + @kaythaney  - I have forwarded a couple of emails that should cover questions/requests above.
I have started capturing the ballots this morning and will continue this week.  There are lots of duplicates so this lessens the typing a bit

**Comment by abbycabs** [comment]
Session etherpads! 
https://public.etherpad-mozilla.org/p/sciencelab-mozfest-2015-session-etherpads

**Comment by abbycabs** [comment]
Follow up emails all sent!

You can see bounced email addresses here (need access):
https://docs.google.com/a/mozilla.com/spreadsheets/d/1hbO_Hdub_vwOmlEvqcbUqFZYv3yvVZr0lSufkIgPbJs/edit?usp=sharing

I ended emails with "We’ll be in touch shortly to see how things are going. Thank you for helping us make research more collaborative, accessible and usable." So we can reach out again in a couple weeks if we want to.

Assigning to Arliss for blog post work

**Comment by stephwright** [comment]
Added more suggestions for new emails on bounces

**Comment by arlissc** [comment]
Blog completed :)

**Comment by arlissc** [comment]
All work completed - closing this issue
