### ISSUE TITLE
resources requirements & sustainability plan

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#23]
Make resources on "resources requirements & sustainability plan" for the fellows project
- [x] figure out what this means
- [x] research
- [x] write draft
- [x] final draft

owner: @acabunoc
cc: @zee-moz 

due date: December 1

**Comment by abbycabs** [comment]
Hey @zee-moz - I probably should have asked this earlier, but I'm not sure what this means. Could you help me understand what you meant by this point?

Sorry

**Comment by zee-moz** [comment]
Hi Abby! Sorry I didn't see this over the weekend. 
We're basically trying to get the fellows to think in advance about the resources and help they'll need for their project--- do they need physical space or server space? will they need $$ for some tech to test it? will they need someone to help who has special skills, like python programming or graphic design? they'll need to look closely at their idea description from KT's deliverable and translate that into a list of needs and requirements. I don't know if this should be done in conjunction with the roadmapping, but it's key in the planning process!

The sustainability bit: how will this project live on after their fellowship is over? who (collaborators, stakeholders) need to be involved to ensure it survives? what level of engagement by those parties is required for a hand-off (assuming there will be one)? basically: if they get kidnapped by aliens or stranded on a deserted island sometime next fall, what will happen to the project?

**Comment by kaythaney** [comment]
hi gang, 
another step i'm not sure we've covered is how their project will apply to a use case other than their immediate own (aka how is this transferable). might be worth having the fellows articulate how their idea applies to a use case other than their own to get them thinking about that. not sure that's right for the sustainability plan or to tack on to the project description exercise i'm working on. @zee-moz - let me know what you think.

**Comment by zee-moz** [comment]
I think it could go in either spot, though maybe better suited to the project description exercise so they get to it sooner (if they're doing these in order that we've listed them) and then reflect that in the sustainability plan, where they're thinking about getting more help and contributors and involvement (they will have more options if they have more potential users/use cases).

**Comment by kaythaney** [comment]
+1. will add!

**Comment by abbycabs** [comment]
In progress: https://github.com/acabunoc/fellows-class-2015/blob/master/resources_requirements.md

**Comment by kaythaney** [comment]
Also, incorporated a line into mine, as well:
https://github.com/mozillascience/fellows-class-2015/blob/master/project_description_exercise.md

On Mon, Nov 30, 2015 at 2:47 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> In progress:
> https://github.com/acabunoc/fellows-class-2015/blob/master/resources_requirements.md
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/plan/issues/23#issuecomment-160738469.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by abbycabs** [comment]
Final Versions here:

https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-resources_requirements.md
https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-sustainability_plan.md

Closing!
