### ISSUE TITLE
roadmap w/ technical requirements

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#25]
Make resources on how to do this "roadmap w/ technical requirements"

For fellows!
- [x] research
- [x] first draft
- [x] final draft

owner: @acabunoc
cc: @zee-moz 

Due date: Dec 12

**Comment by abbycabs** [comment]
draft: https://github.com/acabunoc/fellows-class-2015/blob/master/roadmapping.md

**Comment by abbycabs** [comment]
Note: Still need to incorporate technical requirements here

**Comment by zee-moz** [comment]
Hey, just made a comment (with a bunch of edits) on what you have so far.
let me know if you want to talk tomorrow!

**Comment by zee-moz** [comment]
By bunch of edits, I mean, I edited and updated my comment like a million
times :)

**Comment by abbycabs** [comment]
Roadmapping here: https://github.com/mozillascience/fellows-class-2015/blob/master/explore/3-roadmapping.md
