### ISSUE TITLE
New project call structure

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#29]
We're trying out a new project call format this week (Thurs 11am ET)! Just testing it out, we know it's American thanksgiving :poultry_leg: :us: 

Format:
1. friends of mozilla science / shoutouts to new contributors (on any project)
   - ask Collaborate leads to fill this out before. MC will present it.
2. project updates! All Collaborate projects are invited to give a quick update on their project
3. Best practices in open source - tutorial. This week: What should be in my README?
   - rotating guest presenter?
4. (non-verbal) new volunteers - are you new? what are you looking to do?

To do:
- [x] setup etherpad for new format
- [x] setup hangouts on air for the call
- [x] email / survey Collaborate project leads
- [x] blog about new format
- [x] reach out to community about speaking on best practices (alf + ian?)
- [x] add event to website
- [x] schedule tweets
- [x] reminder email to project leads who haven't filled out form
- [x] host call

owner: @acabunoc

Thoughts / input welcome!

**Comment by abbycabs** [comment]
Etherpad: https://public.etherpad-mozilla.org/p/sciencelab-project-call-nov26

**Comment by abbycabs** [comment]
Hangout info
- To JOIN THE CALL: https://hangouts.google.com/call/peeavwa5ftpu63gmztpf2l2rfia
  - To view the broadcast, click here: https://plus.google.com/events/cg2rtcq42vugrmisef8thu8mivc
- We'll be using Google Hangouts on Air for this call.
  - Please note that this call will be recorded
  -  Miss last call? Here's the recording: https://www.youtube.com/watch?v=aRylnMh6wck

**Comment by abbycabs** [comment]
Survey: http://goo.gl/forms/bZQ5CkLPtL

**Comment by abbycabs** [comment]
Blog: https://www.mozillascience.org/introducing-the-monthly-mozilla-science-project-call

**Comment by abbycabs** [comment]
Reached out to Alf & Ian!

**Comment by kaythaney** [comment]
scheduled a few tweets for today (wednesday). good luck, @acabunoc !

**Comment by abbycabs** [comment]
Recording!
https://www.youtube.com/watch?v=vBAcXkXK7iI
