### ISSUE TITLE
badges follow-on work 

### ISSUE THREAD

**Issue by kaythaney** [mozillascience/plan#30]
:star: :microscope: :heavy_check_mark: 
- [x] follow up with darlene from scistarter on technical support & taxonomy work - @kaythaney (to cc @acabunoc)
- [x] reach out to nate otto about technical backend support - @acabunoc 
- [x] reach out to darlene, connect with nate, non-badgekit ways to support scistarter & paperbadger - @acabunoc 
- [x] revisit taxonomy discussion with darlene in january (connect with CASRAI, other citsci groups) - @kaythaney @acabunoc

**Comment by abbycabs** [comment]
:+1: thanks :)

**Comment by kaythaney** [comment]
np! :information_desk_person:

**Comment by abbycabs** [comment]
emailed Nate, suggested we chat next week!

**Comment by abbycabs** [comment]
Talking to Nate tomorrow

**Comment by abbycabs** [comment]
Credly seems to the best option if you have limited dev resources

**Comment by kaythaney** [comment]
care to reply to darlene with that and maybe an intro to nate? thanks, abby!

On Tue, Dec 15, 2015 at 10:02 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Credly seems to the best option if you have limited dev resources
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/plan/issues/30#issuecomment-164790381.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by abbycabs** [comment]
Yup, I updated the checklist above^ thanks!

**Comment by stephwright** [comment]
@kaythaney okay to close this issue?

**Comment by kaythaney** [comment]
yep!

sent on the move. apologies for typos.
