### ISSUE TITLE
onboarding new community lead

### ISSUE THREAD

**Issue by kaythaney** [mozillascience/plan#31]
New community lead to start on Dec 1. 
- [x] freshen up onboarding materials
- [x] add in zannah's etherpad of mysterious terms
- [x] add new hire to thursday fellows' calls + dec 4th project lead call
- [x] send out welcome email
- [x] introductory MSL blog post

**Comment by stephwright** [comment]
[MozillaLingoBingo.docx](https://github.com/mozillascience/plan/files/43228/MozillaLingoBingo.docx)

**Comment by kaythaney** [comment]
@stephwright ha! did you and @zee-moz create this? :) wonder if it's worth giving to angela and mandy for the new hires for Orlando?

**Comment by stephwright** [comment]
I just threw it together based off @zee-moz 's awesome lingo list.  May want to change up some of the words based on what area the new hires are working in.  Feel free to distribute as you'd like.

**Comment by abbycabs** [comment]
@stephwright that is amazing! Nice work!

**Comment by stephwright** [comment]
All based off @zee-moz 's awesome work!

**Comment by abbycabs** [comment]
closing! I think it's all done :)
