### ISSUE TITLE
Working through Onboarding Docs

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#33]
Reviewing/completing items on the [onboarding checklist](https://docs.google.com/spreadsheets/d/1yt8NdwTdc_vrgWj3_VFtKKOoZiHEH9J_I0jNUKH4C1M/edit?ts=565dc35c#gid=1724807992&vpid=A2).
- [x] Week 1
- [x] Week 2
- [x] Week 3
- [x] Week 4

**Comment by kaythaney** [comment]
go aure!

**Comment by auremoser** [comment]
:) thanks!
