### ISSUE TITLE
Prototyping Deliverables for Fellows

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#35]
owner: @auremoser
consult: @zee-moz @acabunoc

:books: :information_desk_person: 
- [x] schedule chat on prototyping deliverables for fellows (january - february)
  - when are all three of us free?
- [x] meet to discuss deliverables 12/16
- [x] propose structure and delegate if necessary

(was originally [here](https://github.com/mozillascience/site/issues/58))

**Comment by auremoser** [comment]
I'm around pretty much always since I'm new and not on vacation any time soon. We can chat on Friday if that's o.k., or next week, I have the fellows meeting Thursday so I'd like to get feedback from them before we plan the next round. Cool?

**Comment by abbycabs** [comment]
Yup, that makes sense! And I know we chatted a _bit_ about this on Monday. Just put it here so I don't forget :)

**Comment by zee-moz** [comment]
Friday is best for me!

Free all day until 3:30

**Comment by auremoser** [comment]
Fine, I proposed a time, if that doesn't work, just change it, you have change rights: https://public.etherpad-mozilla.org/p/prototype-2015

**Comment by auremoser** [comment]
12/27
- [x] reach out to joey and richard with Zannah's questions, and a proposed approach to the sprints from our meeting 12/16
- [x] modify Arliss's [Prototype Schedule](https://docs.google.com/spreadsheets/d/1iKpicZeDdvBInx4fAGFFkPJP1-vHxkDJ-QicmpbttcQ/edit#gid=1298412634) to include sheet 2 for the "sprint schedule"
- [x] ask Arliss's approval of mods
- [x] push date back to March for the Prototype Phase in [roadmap](https://github.com/mozillascience/fellows-class-2015/blob/master/roadmap.md#prototype-january-march-2016) and in [Prototype Schedule](https://docs.google.com/spreadsheets/d/1iKpicZeDdvBInx4fAGFFkPJP1-vHxkDJ-QicmpbttcQ/edit#gid=1298412634)
- [x] move Zannah's blog post exercise to [Prototype Phase](https://github.com/mozillascience/fellows-class-2015/blob/master/roadmap.md#prototype-january-march-2016) (as we requested the fellow's blogs/rss feeds during the last Fellows call
- [x] draft pre- and post- sprint/week surveys to track progress ([Entry](http://goo.gl/forms/4wu3nkH7WY) and [Exit](http://goo.gl/forms/I6ZRdpvWs7))
- [x] share survey drafts with Abby + Zannah
- [x] publish [survey drafts in the fellows' repo](https://github.com/mozillascience/fellows-class-2015/blob/master/prototype/project_surveys.md)

**Comment by auremoser** [comment]
Hope it's o.k. with everyone, pending feedback from the fellows, I think we're all set.

**Comment by abbycabs** [comment]
:+1: yayy! Nice work @auremoser

**Comment by auremoser** [comment]
my first closed issue! huzzah. thanks @acabunoc
