### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#36]
owner: @acabunoc

December
- [x] Agencies research @kaythaney & @acabunoc
  - consulted: @vazquez

January
- [ ] Start talking to agencies
  - To Contact:
    - [x] [Playground Inc](http://playgroundinc.com/) @acabunoc
    - [x] [Jacknife a.k.a. Oxygen](http://jacknifedesign.com/) @acabunoc
    - [x] [Bocoup](https://bocoup.com/) @kaythaney 
  - Followup meetings
    - [x] Playground (scheduled for 21/1/2016)
    - [ ] Jacknife
    - [ ] Bocoup
    - [ ] MoFo design group
- [ ] Document current site architecture - @acabunoc
- [x] Put together design brief - owner: @acabunoc https://drive.google.com/open?id=1Z2jNumwfLM0d4cgpeF5-N-mEwiGmcWYo4NXHIUIXr7w
  - [x] Project scope
  - [x] [moodboards](https://www.pinterest.com/aure_moser/website/) @auremoser & @zee-moz 
  - [x] Websites we like, sources of inspiration @arlissc & @kaythaney 
    - Add to this issue!
  - [x] Goals & requirements
    - [x] [inventory of current site](https://docs.google.com/spreadsheets/d/1iiUwf_GTXMdV3vB7Tl0h-bCpm1QBumPExkkTL_ktgMQ/edit) @auremoser
  - [x] User stories - journeys for various users
  - [x] Gather assets @acabunoc

Lower priority (may do this after we talk to agencies):
- [ ] create site map

Design brief resources:
- example from MoFo - please feel free to use as inspiration: http://bit.ly/mozdesignbrief 
- more resources on how MoFo design works: 
- http://build.webmaker.org/design 
- http://bit.ly/mofodesignpipeline 

Etherpad: https://public.etherpad-mozilla.org/p/sciencelab-website-redesign
cc: @stephwright would like your input, too!

**Comment by kaythaney** [comment]
thanks, abby!

On Wed, Dec 16, 2015 at 6:02 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> owner: @acabunoc https://github.com/acabunoc
> 
> December
> - Agencies research @kaythaney https://github.com/kaythaney &
>   @acabunoc https://github.com/acabunoc
>   - consulted: @vazquez https://github.com/vazquez
> 
> January
> - Start talking to agencies
> - moodboards @auremoser https://github.com/auremoser & @zee-moz
>   https://github.com/zee-moz
> - Websites we like, sources of inspiration @arlissc
>   https://github.com/arlissc & @kaythaney
>   https://github.com/kaythaney
>   - Add to this issue!
> - Put together design brief - owner: @acabunoc
>   https://github.com/acabunoc
>   - Project scope
>   - Goals & requirements
>     - inventory of current site @auremoser
>       https://github.com/auremoser
>     - create site map
>   - User stories - journeys for various users
>   - Gather assets
> 
> Design brief resources:
> - example from MoFo - please feel free to use as inspiration:
>   http://bit.ly/mozdesignbrief
> - more resources on how MoFo design works:
> - http://build.webmaker.org/design
> - http://bit.ly/mofodesignpipeline
> 
> Etherpad:
> https://public.etherpad-mozilla.org/p/sciencelab-website-redesign
> cc: @stephwright https://github.com/stephwright would like your input,
> too!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/plan/issues/36.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by vazquez** [comment]
#### Toronto Agencies

Some of my fave Toronto agencies:
- [Playground Inc](http://playgroundinc.com/)
- [Huge Inc](http://www.hugeinc.com/)
- [Grip Limited](http://www.griplimited.com/)

Other agencies that have come out with really good work:
- [Sapient Nitro](http://www.sapientnitro.com/en-us.html)
- [Jacknife a.k.a. Oxygen](http://jacknifedesign.com/)
- [Concrete](http://concrete.ca/)
- [Arc and Co.](http://www.arcandco.ca/)

And if you're looking for an experience as opposed to just a website, these agencies are the best at that:
- [Jam3](http://jam3.com)
- [Secret Location](http://thesecretlocation.com/)

**Comment by abbycabs** [comment]
Thanks so much @vazquez! Are these all Toronto?

**Comment by vazquez** [comment]
Yes! I just updated the Heading above

**Comment by abbycabs** [comment]
Scope update!

With mofo working on an MLN-wide (clubs + all fellows groups potentially) [theme](https://github.com/MozillaFoundation/plan/issues/643) and [stack](https://github.com/MozillaFoundation/plan/issues/662) we could leverage in the future, we're going to focus this redesign on two areas.
1. UI/UX refresh of [mozillascience.org](https://mozillascience.org/)
   - **main goals** [in progress]
     - creating an easy to navigate site with clear ways to get involved
     - accurately reflects our current offerings
     - work with broader mofo on the brief -- see if we can start to align with the MLN-wide theming work in progress
   - **constraints**
     - no change to our current backend
     - keep our current wordpress blogging system while we explore shared stack options with mofo
2. [Collaborate](http://mozillascience.org/collaborate) redesign (& potential rewrite)
   - **main goals** [in progress]
     - fold in guides and learning resources
     - spur contributorship

**Comment by kaythaney** [comment]
Update: next steps with bocoup would be to share the current design brief (OK to be in progress) with them, and hop on a call. @acabunoc - they're jess @ bocoup.org + brian @ bocoup.org . Let me know if you need any help!

**Comment by stephwright** [comment]
@acabunoc can we close this?
