### ISSUE TITLE
End of Year Report

### ISSUE THREAD

**Issue by kaythaney** [mozillascience/plan#37]
- [x] finish EOY report, share with funders - @kaythaney
- [x] distill for blog - @kaythaney + others
- [x] publish to figshare - @kaythaney (waiting on a bug fix)
- [x ] add link to the blogpost - @kaythaney
- [x] add additional images to blogpost - @auremoser + @acabunoc to help? (might not be needed)
- [x] tweet out + send to mailing list - @arlissc 
- [x] share blog post highlights + full report link with all-mofo@ email list - @arlissc @auremoser @acabunoc ? 

:fireworks: :clap: :trophy: go team!

**Comment by kaythaney** [comment]
@arlissc @auremoser @acabunoc - could you help share this out by end of day (including with all-mofo list)? ping if you need any help - and thanks in advance!

**Comment by abbycabs** [comment]
I'm collecting images from the past year now!

**Comment by auremoser** [comment]
Can we combine it with the "Happy Holiday's" post, and include the photo from Vidyo with our holiday flair as well?

**Comment by auremoser** [comment]
@acabunoc let me know if I can help! I don't think I can edit the wordpress simultaneously so I'm happy to take over when you are done, just ping me. :)

**Comment by abbycabs** [comment]
@auremoser oh, just saw this! I exited the post and sent you some images

**Comment by abbycabs** [comment]
Holiday post from last year:
https://www.mozillascience.org/happy-holidays-from-the-science-lab

**Comment by auremoser** [comment]
OK, holiday post will be separate then, I've just saved a draft with images. If everyone's o.k. with it, I'll publish. @acabunoc + @kaythaney cool?

**Comment by auremoser** [comment]
Done, thanks @acabunoc : https://mozillascience.org/looking-back-on-2015, we can share it with financial or whomever now, @kaythaney

**Comment by stephwright** [comment]
:heart: the use of @Blahah 's animated logo!!!  well done!

**Comment by stephwright** [comment]
shall I add link to blogpost in the tweet I have scheduled for Wednesday?

**Comment by abbycabs** [comment]
@stephwright - we'll probably have a holiday post go out around then, we can link to that instead, I think!

Emailed all-mofo the post/report!

**Comment by auremoser** [comment]
Emailed our mailing list, but i believe it needs moderator approval, and I just tweeted on our account the blog, so go at it with the re-tweets!

**Comment by auremoser** [comment]
Pending @arlissc mailing list approval of my post, I think we can close this issue, well done all.
