### ISSUE TITLE
Landing pages - working open workshop (WOW!), thursday night meetup

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#38]
owner: @acabunoc

Building two landing pages - they'll both show up under 'Upcoming Events' on our site.
1. Working Open Workshop
2. Open Science Meetup - Berlin (@mozillascience/MSL-Staff anyone have a better name?)
- [x] build WOW page / https://mozillascience.org/working-open-workshop-february-2016
  - [x] add WOW event to database / homepage - link to blog
  - [ ] ~~make event page template~~
    - [x] get text from blog https://mozillascience.org/wow-introducing-working-open-workshops-and-the-open-leaders-cohort
    - [x] make a banner image (comment if you'd like to help)
      - using this as a placeholder: https://s3.amazonaws.com/mozillascience/mozfest-sciencefair.jpg
  - [x] update WOW event in database / homepage - link to WOW page
  - [x] update WOW event in database - add staff & fellows
- [x] build meetup page
  - [x] make event page template (optional -- can probably use default event.jade template)
    - [x] write description
    - [x] make a banner image (comment if you'd like to help)
  - [x] add meetup event to database / homepage - link to meetup page
  - [x] get details - still being finalized

@auremoser if you have time and want to jump into some dev work, happy to work with you on this!

**Comment by auremoser** [comment]
surely, I'm happy to help what would you like me to work on? what's left?
- for the name, maybe 'open science spritzer' or something? we're just doing drinks and lightning talks right? maybe we use 'open science summit' since we're going strictly WOW for the rest of the weekend? I like that it abbreves to OSS.

**Comment by abbycabs** [comment]
@auremoser - do you think we should have an event for the community mixer? I wasn't too sure, so I haven't started on that yet. Happy to let you take that since you're super familiar with our janky event system now!

**Comment by auremoser** [comment]
Oh cool, sure, o.k. I'll start on that.

**Comment by abbycabs** [comment]
Reached out to community designers for a banner image! https://github.com/mozilla/Community-Design/issues/2
- new program Lucy is running

**Comment by abbycabs** [comment]
Landing page look good! Closing this issue :tada: :+1:

**Comment by auremoser** [comment]
Great :)

**Comment by arlissc** [comment]
The landing page looks great ...
