### ISSUE TITLE
Project Call - Jan 28

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#39]
January Project Call checklist!
owner: @acabunoc

General question for @auremoser / @mozillascience/msl-staff - is "project call" too similar sounding to "community call"? I didn't really think about branding when I named the call. Maybe "Collaborate call"?
- [x] make etherpad https://public.etherpad-mozilla.org/p/sciencelab-project-call-jan28-2016
- [x] make event https://mozillascience.org/project-call-jan-28
- [x] setup hangouts on air https://plus.google.com/events/cviv0p6ii40h4eajp37dtb7b2cg
  - speaker link: https://hangouts.google.com/call/cjdrhibc624jrowhiu33djdbzma
- [x] ask someone to emcee
- [x] ask someone to share some 'best practices in open source'

Three weeks before (Jan 7)
- [x] confirm emcee - Max Franz
- [x] confirm 'best practices in open source' - Mike Conley
- [x] email project leads, remind them of call, ask them to add to the agenda

The week of the call
- [x] schedule tweets
- [ ] email mozilla science list
- [x] email project leads with reminder & speaker link to call. Ask them to join 5min early
- [x] send emcee tips to max

Call
- [x] have call

Post-call
- [x] tweet out recording
- [x] update etherpad with recording

**Comment by auremoser** [comment]
I think it's o.k., but I guess when we reboot the website we could decide how we want to brand Collaborate, either we call it that or we call it Projects in the nav+url+page headers and Collaborate is the tool that allows us to surface projects.
Regardless, the name is fine here, you've already done one, let's run with it!

**Comment by abbycabs** [comment]
Good plan, thanks!

**Comment by abbycabs** [comment]
emcee confirmed: @maxkfranz
