### ISSUE TITLE
Community Call

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#40]
January Community Call checklist! 1/14/15
owner: @auremoser
- [x] make etherpad https://public.etherpad-mozilla.org/p/sciencelab-calls-jan14-2015
- [x] make event http://localhost:5000/community-call-jan-14-11-et thanks @acabunoc 

**Thursday before (1/7/16)**
- [x] email mailing list with call announcement
- [x] -7d tweet

**Monday before (1/11/16)**
- [x] email speakers, remind them of call, ask them to add to the agenda, ask to join 5 min early (Carrie, Scott, Andrew, Elizabeth, Fellows)
- [x] schedule tweets

**Call**
- [x] have call

**Post-call**
- [x] followup mailing list blog and sum-up
- [x] tweet out etherpad
- [x] update [wiki](https://wiki.mozilla.org/ScienceLab/Calls) with call archive

**Comment by auremoser** [comment]
Hey @kaythaney, do you usually author a followup post on the blog about the calls? Or mailing list dispatch? Or is it just a pre-call post?

**Comment by kaythaney** [comment]
To date, it's just pre-call, but no reason we can't switch that up. :)

sent on the move. apologies for typos.
