### ISSUE TITLE
Plan for Fellows' Workweek

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#41]
I believe we have a schedule in [this cohort etherpad](https://public.etherpad-mozilla.org/p/cohort-brainstorm-notes), but I thought we could start brainstorming schedule ideas here, any other ideas for engaging with the Berlin scene would be grand, or just +1'ing the following ideas, maybe we don't need this though? @zee-moz, @stephwright @arlissc @kaythaney @acabunoc :

I reached out to a few folks in Berlin, and a friend got back to me with these meetups and some contacts. I'll confirm when they do, and bring more details to this likewise
- [x] reach out to R stats group

http://r-users-group.meetup.com/cities/de/berlin/
meetup about data science with R
- [x] respond to Claudia's mail

http://www.clmb.de/
Claudia is working on how data science can be used for open source software development and collaborative knowledge engineering. She probably also knows other scientist that are interesting for us, we're in email convos now.
### WORKWEEK SCHEDULE
- Demo trainings for WOW with Fellows
- Intro to Berlin Office
- Co-working and share-out about project status in Prototype phase
- Berlin Events?
  - Maybe R meetup outreach or we invite them to the Mozilla Office
  - followup with Claudia and her data science contacts
# 
### SUMMIT SCHEDULE

**FORMAT:**
- Intro to Open Science (presentation and discussion)
  - Why open data? (better under working open essentials?)
- Hands-on, project-based trainings in (with a learn to teach approach)
- Working Open Essentials/How to Open Source Your Project
- Overhaul your Roadmap Session
- Tooling, various options
- GitHub for Leads & Developers; GitHub for contributors; 
  - Github for polite coders/users, or ground rules for collaboration in GitHub
- Community Building++ + Code of Conduct development
- Sharing out work and data-- data management? <<<Steph please add thoughts
  - how to encourage others to share
  - existing sources for data to include in projects? (getting to reuse)
  - what is needed to make shareable (context, metadata)
  - where to share 
- One-on-one project advising and feedback
- Lots of networking time
- Access to curriculum materials and tutorials for further use>>> we need to create these

**STRUCTURE:**
- intros 
- share out about personal experiences 
- mentorship speed dating
- short lecture/intro 20-25 mins
- break into smaller groups
  - 1 hr 15 min working
  - 45 min reflecting/sharing/troublshooting
  - we'll assign faciltators to each team

**Comment by zee-moz** [comment]
In the post-onboarding survey, we'd asked the fellows what trainings would be useful. These are some things that came up: 

-Science Communication/Advocacy (Joey)
-Organizational Change (Richard)
-Curriculum Design (Christie)
(did not see responses from Jason)

If we could do a few hours on one of these that would be great. We'll likely take care of curriculum design as we work through the cohort materials. @auremoser does this fit in with your plan? we could capture what we do for re-use... 

Is there anyone who we could bring in to do something on organizational change, science communication, or advocacy?  @kaythaney @stephwright any ideas? @kaythaney any resources available via the Royal Institution? @acabunoc wasn't there someone at CERN who specializes in science communication? Can we tap resources or knowledge from Mozilla Advocacy team?

**Comment by auremoser** [comment]
Sure, I think that's totally important here, I'm glad we have some structure and some things that the fellows own!
- Are we going to do the curriculum sprint to define some templates for these lessons that we can then test with and modify during the fellows' workweek (for debut at the summit?)?
- Maybe Jason could speak to soliciting participation, or dealing with personal/health data delicately. I think that's a seminar I would totally attend, in tandem with something about survey design, or crowdsourcing for scientific study.

**Comment by zee-moz** [comment]
@auremoser  Clarification: These were trainings the fellows REQUESTED, not that they volunteered to do! I was thinking of these trainings as being targeted to the Fellows, and then re-used for subsequent fellows groups and/or OLC.  

We need to hash out how the fellows trainings will feed into the OLC, and what formats are best! 

As I see it we have three audiences: Fellows, OLC, and the communities/potential contributors the OLC will need to bring into their projects, who need materials and guidance to get started. It's a sort of train the trainers Russian nesting doll! What will be super useful immediately is some data from our OLC invitees about where they are with projects, tech, communities, etc, so we can target workshop stuff appropriately.

**Comment by kaythaney** [comment]
Regarding organizational change, it'd be worth pinging Beatrice Martini
(friend of Mozilla, now working with Gunner at Aspiration). She might even
be able to facilitate. Let me reach out to her.

Also, worth seeing if some of these trainings are better suited for post-
workweek trainings and workshops. For instance, Royal Institution is very
London-based. And there may be other workshops that are externally run
that'd be worth getting the Fellows signed up for.

On Tue, Jan 5, 2016 at 11:47 AM, Aurelia Moser notifications@github.com
wrote:

> Sure, I think that's totally important here, I'm glad we have some
> structure and some things that the fellows own!
> - Are we going to do the curriculum sprint to define some templates
>   for these lessons that we can then test with and modify during the fellows'
>   workweek (for debut at the summit?)?
> - Maybe Jason could speak to soliciting participation, or dealing with
>   personal/health data delicately. I think that's a seminar I would totally
>   attend, in tandem with something about survey design, or crowdsourcing for
>   scientific study.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/plan/issues/41#issuecomment-169057665.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by auremoser** [comment]
Update workweek schedule: [mslparty-WOW](https://public.etherpad-mozilla.org/p/wow-mslparty)
