### ISSUE TITLE
WOW Tasks

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#42]
WOW task checklist! 1/14/15
owner: @auremoser
- [x] manage [spreadsheet](https://docs.google.com/spreadsheets/d/176QgQb2dkV6dQpScKU70Wv1EGxtNXwyQtrkJcTci5F4/edit#gid=0) of invitees  (8 hrs)
- [x] create friendly personable, conversational email with event details, log responses (6 hours)
  - [x] round 1 invites send 12/22
  - [x] round 2 invite send
- [x] collecting info/surveys results, bios (2 hours)
- [x] respond with travel and visa arrangements
- [x] investigate options for transcription; connect with Amira about making event accessible for all audiences (4 hours)
  - [x] contact Amira for additional tips
  - [x] contact [Mirabai](http://stenoknight.com/) for availability and pricing
  - [x] contact [Norma Miller](http://www.whitecoatcaptioning.com/contact) if necessary
  - [x] read up on [designing accessible spaces](http://zines.barnard.edu/blogs/deafula-7-accessible-spaces)
- [x] help with curriculum (10 hours)  
- [x] get fellows onboarded to event plan, arrange travel with Arliss (3hrs)

**Comment by kaythaney** [comment]
WOW Action Items (from 1/6/16 meeting)
ACTION ITEMS:
- [x] Send @auremoser  Expensify instructions - @arlissc 
- [x] Send out updated reimbursement instructions to participants / invitees - @auremoser 
- [x] Reach out to Linda/Anabelle - for early week  - @auremoser 
- [x] Venue + planning for Thursday night - @arlissc  + @kaythaney
  - [x] @auremoser to link both with peter from berlin open science meetup, talk collaboration
- [x] Venue for big group dinner on Friday evening - @arlissc  
- [ ] Compile list of dining recommendations (for Saturday) - @arlissc  + @kaythaney
- [x] Draft expectations email to send out week prior -  @auremoser  (+ @kaythaney as needed)
- [x] Adapt @auremoser 's [Open Source checklist](https://github.com/mozillascience/plan/issues/34#issuecomment-164818133) for a pre-survey - @zee-moz @auremoser  + @acabunoc 
- [x] Link up with Berlin Open Science meetup - @auremoser  to intro @arlissc  @kaythaney to Peter, loop in Jon T. 
- [x] Reach out to Beatrice - @kaythaney to email intro @zee-moz 
- [x] @zee-moz to outline next steps for curriculum / resource creation
- [x] @stephwright to follow up on swag (Sci Lab stickers are ordered!)
  - [x] Ping Sarah Allen about any leftover MozFest notebooks @stephwright
    - [x] Place ServiceNow order to get notebooks, pencils, and bags to Berlin @stephwright
  - [x] Order new Research Fox stickers when new fox design available @kaythaney 
  - [x] Order new USB drives @stephwright

**Comment by kaythaney** [comment]
@acabunoc @auremoser @acabunoc @zee-moz @stephwright feel free to add to this and / or move to another thread if easier!

**Comment by stephwright** [comment]
There are leftover notebooks from Mozfest and Sarah Allen said she'd be happy to let us have them for WOW as well as bags and pencils.

**Comment by auremoser** [comment]
More tasks from 1/8
[Team call etherpad](https://public.etherpad-mozilla.org/p/sciencelab-teamcalls-jan08-2016)
- [x] email participants with expensify details 
- [x] get boutique requests for travel (transcriptionists, some students) to Pamela
- [x] make sure accommodation options are sent out
- [x] draft intro onboarding email with @zee-moz ' [survey](https://docs.google.com/forms/d/12Np-N8bj-3P90t12QPydTUcoHWNtNb55Br8RBBk4Yqg/viewform)
  - [x] send to @kaythaney for approvals
- [x] send transcriptionist training vocabulary [here](https://docs.google.com/document/d/1UJIIMupcsoNs--4pOfCy83jQ7WgK4AVO6nHTCecrw6g/edit?ts=569581d7#)
  Owner: @auremoser

**Comment by abbycabs** [comment]
More [tasks from 1/12](https://public.etherpad-mozilla.org/p/cohort-brainstorm-notes)

## Sketch outlines for 10 minute presentations

(will build materials off of these) 
- [x] Roadmapping - @acabunoc 
- [x] Contributor Guidelines - @auremoser  (CONTRIBUTING.md)
- [ ] Events + Sprints - @arlissc  (to contact Madeleine)
- [x] Data - @stephwright  (to contact Christie) (also here: https://github.com/mozillascience/plan/issues/48)
- [x] Code of Conduct - @kaythaney  + @auremoser  
- [ ] Personas + Pathways - @zee-moz 

owner: @zee-moz

**Comment by kaythaney** [comment]
@zee-moz aurelia and i have been capturing the CoC (and for her, github netiquette) outlines in this pad. CoC starts under line 211: https://public.etherpad-mozilla.org/p/WOW-contrib (cc @auremoser)

**Comment by zee-moz** [comment]
@kaythaney @auremoser can you add your links and use the checklist in the WOW repo? more info and process stuff there. https://github.com/mozillascience/working-open-workshop/issues/6

**Comment by auremoser** [comment]
@zee-moz would you like me 
- [ ] to split them into separate etherpads then? 
- [ ] or make them into markdown documents in the repo

**Comment by kaythaney** [comment]
@zee-moz @auremoser code of conduct handout is UP: https://github.com/mozillascience/working-open-workshop/blob/master/handouts/code_of_conduct.md

**Comment by auremoser** [comment]
Looks awesome! I'll follow suit with the Contributing.md file :). Thanks so much @kaythaney for doing such a stellar job on this.
