### ISSUE TITLE
Mozilla Science Study Groups

### ISSUE THREAD

**Issue by kaythaney** [mozillascience/plan#5]
:raising_hand: + :books: 
- [x] @kaythaney to set up and populate msl-study-group mailing list
- [x] follow up email to set up next call - @kaythaney
- [x] fork assay / work out clean way to share lessons across groups - @acabunoc 
- [ ] calendaring across groups! - @acabunoc 
- [x] contributor guidelines - @stephwright & @kaythaney (pick up after MozFest)
- [x] regular calls strategy / schedule - @auremoser 
- [ ] regional strategy  (pick up dec 2015)

**Comment by abbycabs** [comment]
email worked for me! :+1:

**Comment by abbycabs** [comment]
Note on the fork assay - this is done for study group site features (calendar, member page), not lessons. Lessons are using a cleaner submodule system.

I expect the site features will die down over time as the Study Groups mature. In the meantime, fork assays reasonable to deal with :smile_cat: I'll check that box off for now, and focus on the calendaring issue!

**Comment by stephwright** [comment]
Contributor guidelines to be presented to study group leads at 12/4 call

**Comment by kaythaney** [comment]
adding @auremoser to this

**Comment by stephwright** [comment]
Hey @auremoser and @zee-moz ... are we at a point where we want to pull what we want out of this issue, close it and start a new one w/ new plans for Study Groups or how should we proceed on this?

**Comment by auremoser** [comment]
Sounds good! 

I think we could revisit the calendar setup, roles for comms, and some index of assets and locations, shareable by all.

I've created an issue for this here #97

**Comment by zee-moz** [comment]
Thanks for making the new issue.  I'll take a look Wednesday after PTO--
rushing to get some orientation stuff done this afternoon.
Thanks!
Z

**Comment by stephwright** [comment]
Thanks both!
