### ISSUE TITLE
Explore Phase: Fellow Blog Feedback

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#59]
**owner**: @auremoser

Review and process explore phase blogs and get them posted
- [x] review/merge queued blogs in wordpress
- [x] make schedule and alert team
  - [x] Joey [ 2/23/16 ]
  - [x] Jason [ 2/25/16 ]
  - [x] Christie [ 2/18/16 ]
  - [x] Richard [ 2/16/16 ]
- [x] process interview blogs and review
- [x] reach out to fellows about posting blogs on their blogs
- [x] create summary blog with choice interview excerpts

**Comment by kaythaney** [comment]
when are we thinking the staged posts on the MSL blog will go live again?

**Comment by auremoser** [comment]
I was going to stage them for this week but it got too crazy. I think I'll try to make them for Monday after Wow, or maybe the tuesday after the WOW wrap up post.

**Comment by auremoser** [comment]
Content Calendar available [here](https://docs.google.com/spreadsheets/d/18IACe9eSaDXkILieeQYmDHxCsM9pBNOqFFDtswzdG98/edit#gid=0)
