### ISSUE TITLE
Blog about Research Fox Kits

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#60]
**owner**: @auremoser
**cc**: @stephwright @kaythaney 
- [x] create form/survey to solicit addresses: http://goo.gl/forms/Dow83mjMzT
- [x] write [draft blog](https://public.etherpad-mozilla.org/p/msl-swagkits)
- [x] gather image assets
- [x] followup with folks who asked for stickers already, get them to fill out the form
- [x] select "winners"
- [x] assemble swag kits (padded envelopes)
- [x] assemble smaller sticker sets (envelopes)
- [x] sent them out by Feb. 17 (post WOW)

**Comment by stephwright** [comment]
@auremoser do you have a link to the swag assets that you could put in here?  Is it in Google Drive? Dropbox? or in GitHub somewhere?
