### ISSUE TITLE
Setup OLC Meetings

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#65]
For each meeting, on the etherpad, put their main objectives and timeline at the top of the pad

For @acabunoc:
- [x] [Madeleine - PhageParser](https://public.etherpad-mozilla.org/p/wow-phageparser)
- [x] [Bastian](https://public.etherpad-mozilla.org/p/wow-bastian)
- [x] [Achintya - Open Cosmics](https://public.etherpad-mozilla.org/p/wow-achintya)
- [x] [Brian](https://public.etherpad-mozilla.org/p/wow-brian)
- [x] [Repo doctor group](https://public.etherpad-mozilla.org/p/wow-harun)
- [x] [Robert](https://public.etherpad-mozilla.org/p/wow-robert)
- [x] [Demitri](https://public.etherpad-mozilla.org/p/wow-demitri)
- [x] [Chris](https://public.etherpad-mozilla.org/p/wow-christopher)

For @auremoser:
- [x] [Madeleine - UofT coders study group](https://public.etherpad-mozilla.org/p/wow-madeleine)
- [x] [Jon](https://public.etherpad-mozilla.org/p/wow-jon)
- [x] [Patricia & Achintya - CERN study group](https://public.etherpad-mozilla.org/p/wow-patricia)
- [x] [Harry](https://public.etherpad-mozilla.org/p/wow-harry)
- [x] [Amel, Fatma, Anelda](https://public.etherpad-mozilla.org/p/wow-amel-et-al)

Both:
- [x] [Anna](https://public.etherpad-mozilla.org/p/wow-anna)
- [x] [Kirstie](https://public.etherpad-mozilla.org/p/wow-kirstie)
- [x] [Oliver](https://public.etherpad-mozilla.org/p/wow-oliver)
- [x] [Peter](https://public.etherpad-mozilla.org/p/wow-peter)
- [x] [Tim & Igor](https://public.etherpad-mozilla.org/p/wow-tim)

**Comment by abbycabs** [comment]
To do before the 2nd mtg with each group. I'll put an example up soon!

**Comment by auremoser** [comment]
Thanks Abby!

**Comment by abbycabs** [comment]
Sample up on Bastian's etherpad: https://public.etherpad-mozilla.org/p/wow-bastian

Let me know if this looks good to you -- feel free to modify!

**Comment by auremoser** [comment]
Did all for the next date, except @acabunoc and a few for the following week, thanks for patience!
