### ISSUE TITLE
[mozsprint] Special Questions for Open Data submissions

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#71]
Identify questions needed for open data submissions.
Such as:
Data Stuff
- where is the data stored ? 
  - Is it accessible by everyone?
  - If not, what needs to happen so participants can access?
- in what format is the data?
  - do participants need special and/or non-open software to use the data?
- are there licensing (or other) restrictions on the data for reuse?
- how large is the data file/s?

Brian Bot / ~~Ali Swanson - want to bring data to the sprint~~
- see people come to the sprint to do some analysis, maybe do some data cleaning  
  Brian - human data - need to request access (6 days) - can bring him in to do a datahack  
  ~~Ali - Serengeti - do some analysis~~

---

Migrated from https://github.com/mozillascience/global-sprint-2016/issues/3

**Comment by stephwright** [comment]
@acabunoc 
Have we had any submission around open data yet?

**Comment by abbycabs** [comment]
https://github.com/mozillascience/global-sprint-2016/labels/%5BTrack%5D%20Open%20Data

**Comment by stephwright** [comment]
Duh... labels.  Thanks @acabunoc

**Comment by abbycabs** [comment]
Also, feel free to re-label! Most of those are self-sorted
