### ISSUE TITLE
Add MSL Commitments to Gantt chart

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#80]
- [ ] add [dates + milestones](https://docs.google.com/spreadsheets/d/12Wur2T-mINVWl5Y58EgsjufB9vFLJ_KC0hUhVTjKOj4/edit?ts=5706c0d0#gid=0)
- [ ] fix tooltip issue

**Comment by stephwright** [comment]
Hey @auremoser ... where are we with this one?

**Comment by auremoser** [comment]
@stephwright, no where right now. 
I haven't had time to update. I'll put it on my list for next week.

**Comment by stephwright** [comment]
@auremoser is it worth doing this at this time or maybe wait until we have the new strat plan stuff available?

**Comment by auremoser** [comment]
Good point, I can at least update the tentpole things in that linked spreadsheet, and then once we're ready with the strat plan, it might make sense to create a "status" site, like one with the map you mentioned and this gantt chart #workingopen
