### ISSUE TITLE
Fellows' Phase 3 Exercises

### ISSUE THREAD

**Issue by auremoser** [mozillascience/plan#82]
Assembled materials for test/share phase (starts May 15) as listed in the [fellows' repo roadmap](https://github.com/mozillascience/fellows-class-2015/blob/master/roadmap.md#testshare-may-june-2016)

Here are the draft exercises:
- [Meta résumé exercise](https://github.com/mozillascience/fellows-class-2015/blob/master/test/1-resume.md)
- [Documentation exercise](https://github.com/mozillascience/fellows-class-2015/blob/master/test/2-documentation.md)
- [Retro-blogging](https://github.com/mozillascience/fellows-class-2015/blob/master/test/3-retro-blogs.md
- [Event Planning](https://github.com/mozillascience/fellows-class-2015/blob/master/test/4-event.md)

It would be lovely if @acabunoc @kaythaney @zee-moz @stephwright could review one of the above lessons and +/- 1. I'm impartial so you can edit and push directly without consulting me if you find errors or think aspects are unclear.

**Comment by abbycabs** [comment]
Read through these! Nice work @auremoser 👍 💯 🎉 

I especially like the Meta Resume and the reto-blogging seems like a great way to encourage the next set of fellows.

The Documentation exercise itself is great! By adding to phase 3, I'm slightly worried that the Documentation exercise is encouraging people to leave their project documentation to the very end? A lot of our WOW stuff asks people to document all the time.

**Comment by auremoser** [comment]
Thanks @acabunoc , fair point well-made.
I think the goal here was to make sure that they document, period, or polish their documentation. I'll add some language to clarify that. Thanks!

**Comment by auremoser** [comment]
Added 👍

**Comment by abbycabs** [comment]
👍

**Comment by zee-moz** [comment]
These look awesome! I corrected a typo and added a section heading
(Connections) that seemed to be missing from the resume doc. I LOVE the
resume exercise-- it's something I think could be helpful from the
beginning, and fellows could fill it out as they go. A good way to measure
ongoing progress.

Early in the fellowship, we asked them to think about project
sustainability. I'm not sure how much to that sunk in, but now as they are
wrapping up their fellowships, I wonder if it's a good time to bring this
up again-- for each project, what is the plan for expansion, ongoing work
or maintenance, who are partners, is the project a one-off, etc...

z

**Comment by auremoser** [comment]
Yes, totally @zee-moz . I linked to the sustainability plan in the documentation exercise, so hopefully they'll go back and review! Thanks for the corrections!

**Comment by zee-moz** [comment]
Cool. I wonder if this is something we should require for all projects, not
just the one that they are documenting-- like, if we want to refer to or
follow up with the project in future (for reporting, for materials for
funders, for our own assessment of fellowship program impact), where and in
what state can we expect to find it, who's maintaining, etc.

z

**Comment by auremoser** [comment]
Yeah, I think that makes sense, it's something I could probably work into the closing activities/launch in august, maybe we could ask them in their exit interviews to revisit sustainability..
