### ISSUE TITLE
Newsletter isn't on the blog

### ISSUE THREAD

**Issue by solstag** [mozillascience/plan#86]
Hi,

I always find the Mozilla Science newsletter quite interesting, however I also find it really disturbing that I can't point people to a post of it, whether on the Mozilla Science Blog or elsewhere.

I would like to ask that the newsletter be posted to the blog as well, so we can reference it through a URL and also to make it clear it has a CC-BY license so it can be reused elsewhere.

I'm filing this issue because at the Ciência Aberta group we're planning to translate the newsletter and post it to our blog and mailing list, and it would be much easier to pass it along for potential translators, or even reference old issues, if there the newsletter could be found on the web.

Cheers!

**Comment by solstag** [comment]
By the way, I'm aware that the newsletters can be found on the mailing list archives.

Unfortunately, mailman archives are even less convenient and publicly visible than my mailbox. : P

There's also the positive aspect that it would fit nicely into the blog, and make the license clear. =)

**Comment by abbycabs** [comment]
flagging @auremoser ^

**Comment by auremoser** [comment]
Thanks for the suggestions @solstag ! Our newsletters are publicly archived on TinyLetter, which is a little more user-friendly than mailman when it comes to the interface!

http://tinyletter.com/sciencelab/archive
It is linked off our subscribe page: http://tinyletter.com/sciencelab/

We like to keep the blog tidy with posts that we then reference in the newsletter, but I can try to cross-post this month and see how things are received. 

Thanks!

**Comment by solstag** [comment]
Cool, I had never seen the tinyletter page. Here's our first translation, for May:
https://www.cienciaaberta.net/newsletter-maio-mozilla-science/
I see the June newsletter has also been published, but I never got it by mail.
Have you ceased sending it to the mozilla science mailing list? So, should I subscribe specifically for the newsletter?
You could warn the list about that, don't remember seeing a notice.
Cheers!

PS: Also, a content license is still missing in the newsletter, since it's not yet on the blog.

**Comment by auremoser** [comment]
Thanks for the feedback @solstag , we just switched to tiny letter a few months ago and we've been having troubles getting it to post to the regular list. I send out a tweet about the tinyletter subscription about once a month, but for a time I had thought it was going to the mozillascience list so I didn't re-post.

For the time being, please do subscribe to the tiny letter page. 

Thank you for the translation! Have a lovely day!

**Comment by solstag** [comment]
Got it. You too!
