### ISSUE TITLE
DNA match game!

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/plan#9]
:microscope: 

As people enter the science fair, give them a sticker with a 4 bp DNA snippet. They have to bring their match (exact or complement) to the #openscience table / floor to get a prize!
- [x] order shipping labels to the London office / @kaythaney 
  - http://www.amazon.co.uk/Sheets-Shipping-Labels-White-Address/dp/B006GQ4OHC/ref=sr_1_6?ie=UTF8&qid=1446159734&sr=8-6&keywords=shipping+labels
  - http://www.amazon.co.uk/Self-Adhesive-Addressing-Shipping-Printable-compatible/dp/B00IJZP3H8/ref=sr_1_4?ie=UTF8&qid=1446161480&sr=8-4&keywords=labels4u+8+labels+per+sheet
  - 8 labels per sheet / 1200 labels total
- [x] design labels / @acabunoc
- [x] figure out how to use open office to print labels from a spreadsheet w/ the DNA snippets / @acabunoc
- [x] design ballot people will fill out to win!
- [x] print 1000 labels! / @acabunoc
- [x] figure out who will stand at the entrance and stick these on everyone. Fellows will be busy.

owner: @acabunoc

**Comment by abbycabs** [comment]
Right now, with 256 (4^4) unique DNA snippets, there would be ~7 people that would match you at the festival if we print 1000 labels (3 if you don't know how dna complements work)

Should we make it more likely to find your match?

**Comment by kaythaney** [comment]
hrm ... that might be easier, get more interaction. 

also, can see if we can get those running the registration desk to hand out. :)

**Comment by abbycabs** [comment]
sounds good - I'll aim for 100 unique snippets (50 unique + complements) to make things more likely :)

+1 registration desk work!

**Comment by abbycabs** [comment]
![screen shot 2015-11-04 at 16 40 12](https://cloud.githubusercontent.com/assets/617994/10944793/c082f702-8312-11e5-9496-758b844857a7.png)

Went for even more likely!

24 snippets + their complements = 48 unique codes in the pdf:

[dna.pdf](https://github.com/mozillascience/plan/files/27255/dna.pdf)

**Comment by abbycabs** [comment]
If people find their match, they can bring them to the #openscience floor / table, then they can enter the #openscience raffle. Enter for a chance to win!

Questions
- what will people win? Preferably something we can email them. Can we give them a giftcard of some sort, @kaythaney?
- where can we find a box to hold the ballots?

On the entry ballot:
- name
- email
- [ ] send me info on how I can start an open science study group
- [ ] send me info on open science projects I can contribute to
- [ ] add me to your mailing list

**Comment by abbycabs** [comment]
raffle ballots
[raffle_mozfest.pdf](https://github.com/mozillascience/plan/files/27355/raffle_mozfest.pdf)

![screen shot 2015-11-04 at 18 34 24](https://cloud.githubusercontent.com/assets/617994/10947899/b4e164fa-8322-11e5-8e24-38ded1a05420.png)

**Comment by stephwright** [comment]
Can't wait to see how this plays out!

**Comment by abbycabs** [comment]
game is live and AWESOME!

**Comment by kaythaney** [comment]
and gift card is AWARDED.

**Comment by stephwright** [comment]
:trophy:
