### ISSUE TITLE
Strategic Planning Agenda 10/10-11/2016

### ISSUE THREAD

**Issue by stephwright** [mozillascience/plan#92]
Please add items @auremoser and @zee-moz 
- [ ] Prioritization of projects / responsibilities
- [ ] Strategic Community Engagement Plan
  - [ ] Expanding Network: DLF, OpenCon, AAAS, ELPUB, Libraries
- [ ] Communication Plan
  - [ ] Marketing and PR plan
- [ ] Assessment & Metrics needs
- [ ] Budget + financial planning
  - [ ] fundraising needs
- [ ] Maximizing resources / effort
  - [ ] Study Groups -> Clubs
  - [ ] Website -> events, membership
  - [ ] Fellowships
  - [ ] Global Sprint
  - [ ] Mozfest
- [ ] review all our resources
  - [ ] fellows stuff
  - [ ] lessons
  - [ ] rando exercises for quality control

**Comment by auremoser** [comment]
I added some discussions of budget and marketing, so we know for example: 
- When do we send people swag and promotional materials?
- What are our expectations for ad-hoc mini-grants (like a blog post from the mini-grant applicant)?
- What are some ceilings/basic numbers to keep in mind and the appropriate process for requesting approvals?

**Comment by stephwright** [comment]
Awesome!  Thanks @auremoser !
