### ISSUE TITLE
Add info for Appreciation Nominations

### ISSUE THREAD

**Issue by stephwright** [mozillascience/plan#93]
Ask from: @acabunoc , @arlissc , @auremoser , @zee-moz , @kaythaney 
Due 9/16

Please fill in as many fields as you can in this spreadsheet per our discussion at the Staff mtg:
https://docs.google.com/spreadsheets/d/1OAGV4EIgc2qe_-HPy3S0hiQTwG19DVxgalleVbIln3k/edit#gid=475353825

**Comment by auremoser** [comment]
Gave feedback on everyone I knew, and tried to fill out all fields I could!

**Comment by stephwright** [comment]
Thankyou! 🙇

**Comment by stephwright** [comment]
Thanks for the feedback everyone... I submitted our spreadsheet to Rizwan.  Some of you may be asked to provide follow-up.  Closing this issue for now.  Likely to come up again in future as we plan for how we want to track and recognize contributions.
