### ISSUE TITLE
Volunteers for Study Group Orientation calls week after Thanksgiving

### ISSUE THREAD

**Issue by stephwright** [mozillascience/plan#99]
Need volunteers to talk about Open Science on SG orinetation calls week after thanskgiving

**Comment by auremoser** [comment]
I'm fine helping out again; I think Zannah and I made a good team. 

Though, @acabunoc probably has a more informed background in bioinformatics. We could also ask one of the fellows, no?

**Comment by zee-moz** [comment]
Teon and Kirstie are interested in helping out, per my request on the fellows gitter chat. FYI here are the times for the call. @stephwright can you join us at one? i will send around invites for the calls :) 

Thursday, December 1 at 5pm UTC (9am PST, 11am CST, 12pm EST)
Friday, December  2 at 9am UTC (10am West Africa Time, 11am Eastern European Time,  2:30 pm Indian Standard Time, 4pm Indonesia Western Time,  note this is **4 am EST, 1 am PST**)

**Comment by auremoser** [comment]
Excellent! Let me know if you need help with the Friday...4am EST is still probably better than 1am for PST.

**Comment by stephwright** [comment]
I will join in on the Thursday one... have it in my calendar now.  Thanks for being willing to do the 4a stint, @auremoser .

**Comment by zee-moz** [comment]
@auremoser @stephwright awesome! I am hoping that @cbahlai might be able to drop in to plug her course. Here's a rough plan for that session, we may do item 2 or item 3 or both, depending on who's available for each call. 

###Meeting 3: Open Science 101
(Co-hosts: Kirstie, Teon, etc etc)
1. Intros and Updates
    * Name, location
    * What’s new? 
    * Check in on goals
2. Open Data & Reproducible Research Resources
     * Christie’s course - lightning demo?
     * ODT with Steph - lightning demo?
3. Fellows/Community members on Open Science Stuff
   * Teon on whatever he wants
   * Kirstie on whatever she wants
   * Achintya?
4. Open Science Discussion: Landscape, Challenges and Responses 
    * How is open science viewed at your institution, in your lab? 
    * What practices might be easily adopted? 
    * What the your biggest blockers? 
    * What could help? 
    * What are challenges you often hear to open practice? 
    * What are your own concerns or hesitations?
    * Brainstorm responses together
5. Open Q&A on section 4

**Comment by cbahlai** [comment]
OOh, I can do that!

**Comment by stephwright** [comment]
I'm down with that, too!

**Comment by auremoser** [comment]
+1 feel free to invite me to whatever meeting
